name: Bug Report
description: Report a bug or issue with AuroraSEO
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: When I run aurora-seo generate, I get an error...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run `aurora-seo init`
        2. Configure with '...'
        3. Run `aurora-seo generate`
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened instead
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error output
      description: Any error messages or logs
      render: shell

  - type: input
    id: aurora-version
    attributes:
      label: AuroraSEO version
      description: Run `npx aurora-seo --version`
      placeholder: 1.0.0
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: Run `node --version`
      placeholder: v18.17.0
    validations:
      required: true

  - type: input
    id: nextjs-version
    attributes:
      label: Next.js version
      description: From your package.json
      placeholder: 13.4.0
    validations:
      required: true

  - type: dropdown
    id: router-type
    attributes:
      label: Next.js Router
      options:
        - App Router (Next.js 13+)
        - Pages Router (Traditional)
        - Both
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here
